version: "3.9"
services:
  redis:
    image: "redis"
    ports:
      - "6379:6379"
  reposerver:
    image: "quay.io/argoproj/argocd:latest"
    command:
     - "--redis"
     - "redis:6379"
    ports:
      - "8081:8081"
    entrypoint: argocd-repo-server