site_name: GOFF
site_url: https://example.com/
nav:
    - Home: index.md
    - Examples: examples.md
    - Integrations: integrations.md
    - Build: build.md
theme: readthedocs
plugins:
    - search
    - markdownextradata:
        jinja_options:
          variable_start_string: "#{{"
extra:
  goff:
    version: !ENV [GOFF_VERSION, 'v0.0.0']