stages:          # List of stages for jobs, and their order of execution
  - merge

create_comment_helm:
    stage: merge
    image: quay.io/puzzle/goff:latest
    script:
     - echo "Target branch $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
     - git clone -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME --single-branch $CI_REPOSITORY_URL /tmp/checkout/target
     - mkdir -p /tmp/source
     - mkdir -p /tmp/target
     - helm template mychart ./helm/mychart --output-dir /tmp/source/out
     - helm template mychart /tmp/checkout/target/helm/mychart --output-dir /tmp/target/out
     - goff diff "/tmp/source" "/tmp/target" --output-dir /tmp/
     - glab auth login --hostname gitlab.puzzle.ch -t $GITLAB_ACCESS_TOKEN
     - glab mr note -m "$(cat /tmp/diff.md)" $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes: 
        - helm/**/*
     
create_comment_kustomize:
    stage: merge
    image: quay.io/puzzle/goff:latest
    script:
     - echo summy
     - echo "Target branch $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
     - git clone -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME --single-branch $CI_REPOSITORY_URL /tmp/checkout/target
     - mkdir -p /tmp/source
     - mkdir -p /tmp/target
     - cd kustomize
     - goff kustomize build . --output-dir=/tmp/out/source
     - cd /tmp/checkout/target/kustomize
     - goff kustomize build . --output-dir=/tmp/out/target
     - goff diff "/tmp/out/source" "/tmp/out/target" --output-dir /tmp/
     - glab auth login --hostname gitlab.puzzle.ch -t $GITLAB_ACCESS_TOKEN
     - glab mr note -m "$(cat /tmp/diff.md)" $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes: 
        - kustomize/**/*


create_comment_argo:
    services:
      - name: quay.io/argoproj/argocd:latest
        alias: repo-server
        entrypoint:
          - "/usr/local/bin/argocd-repo-server"
    stage: merge
    image: quay.io/puzzle/goff:latest
    script:
     - echo "Target branch $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME"
     - git clone -b $CI_MERGE_REQUEST_TARGET_BRANCH_NAME --single-branch $CI_REPOSITORY_URL /tmp/checkout/target
     - mkdir -p /tmp/source
     - mkdir -p /tmp/target
     - goff argocd "./argocd" --repo-server="repo-server:8081" --output-dir=/tmp/source/
     - goff argocd "/tmp/checkout/target/argocd"  --output-dir=/tmp/target/
     - goff diff "/tmp/source" "/tmp/target" --output-dir /tmp/
     - glab auth login --hostname gitlab.puzzle.ch -t $GITLAB_ACCESS_TOKEN
     - glab mr note -m "$(cat /tmp/diff.md)" $CI_MERGE_REQUEST_SOURCE_BRANCH_NAME
    rules:
    - if: $CI_PIPELINE_SOURCE == 'merge_request_event'
      changes: 
        - argocd/**/*
