apiVersion: v1
kind: Service
metadata:
  name: integration-non-gpu-simple-service
  namespace: integration
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: trivial-go-web-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    codefresh.io/app: simple-go-app
  name: integration-non-gpu-simple-deployment
  namespace: integration
spec:
  replicas: 3
  selector:
    matchLabels:
      app: trivial-go-web-app
  template:
    metadata:
      labels:
        app: trivial-go-web-app
    spec:
      containers:
      - env:
        - name: UI_THEME
          value: dark
        - name: CACHE_SIZE
          value: 1024kb
        - name: PAGE_LIMIT
          value: "50"
        - name: SORTING
          value: descending
        - name: N_BUCKETS
          value: "48"
        - name: ENV
          value: integration-non-gpu
        - name: GPU_ENABLED
          value: "0"
        - name: ENV_TYPE
          value: non-prod
        - name: PAYPAL_URL
          value: staging2.paypal.com
        - name: DB_USER
          value: non-prod-user
        - name: DB_PASSWORD
          value: non-prod-password
        image: docker.io/kostiscodefresh/simple-env-app:2.0
        imagePullPolicy: Always
        name: webserver-simple
        ports:
        - containerPort: 8081
